Refactor integration test step with Docker Compose
Updated integration test step to use Docker Compose for service management and added error handling. Adding "special" integration-test step on go.yaml workflows. This will be fixed later on in the Makefile and documentation will also be updated.

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -36,5 +36,12 @@ jobs:
     - name: test
       run: make test
 
+    # This step will be fixed later on in the Makefile.
     - name: integration-test
-      run: make integration-test
+      run: |
+        @echo "Starting services..."
+        docker compose up -d --build
+        @echo "Running integration tests..."
+        go test ./test/integration_tests || (echo "Tests failed, stopping services..."; docker-compose down; exit 1)
+        @echo "Stopping services..."
+        docker compose down
